[configuration]
    download_server = "0.0.0.0" #to download batches/runners
    upload_server = "0.0.0.0" #where to upload model
    upload = true
[configuration.validation]
    test_size = 0.10 #validujeme na casti testovacich dat
    runners = ["5297fba1-0274-49bf-adc7-9c0395754550"] #nad seznamem runner
    batch = "" #nad konkretnim batchem
[configuration.model]
    name = "model2uploaded1"
    version = 0.1
    note = "poznamka"
    input_sequences = 50
    use_bars = true
    bar_features = ["volume","trades", "close","high","open","low", "vwap","index"]
    ind_features = ["slope", "ema50"] #, 'firstbar_open','last_close','last_open']
    target='target'
    target_reference='vwap'
    #train_runner_ids = None
    train_batch_id = "34e754c3"
    train_epochs = 10
    train_remove_cross_sequences = true
[configuration.architecture]
    name = "modelConv1D"  #name of architecture plugin
    #modelLSTM #modelConv1D (with learning_rate param)
[configuration.architecture.params]
    learning_rate = 0.0001