    #download_server = "142.132.188.109"
    #upload_server = "142.132.188.109"
    download_server = "0.0.0.0"
    upload_server = "0.0.0.0"

    #test 5.161.179.223
    #upload_server = "5.161.179.223" #where to upload model
    #download_server = "5.161.179.223" #to download batches/runners
    upload = true
[validation]
    test_size = 0.0 #validujeme na casti testovacich dat
    runners = ["96fad44c-7a7a-4833-8915-6cc5180593a0"] #nad seznamem runner
    batch = "" #nad konkretnim batchem
[model]
    name = "modelMulti"
    version = 0.1
    note = "multiinput test"
    #train_runner_ids = ["96fad44c-7a7a-4833-8915-6cc5180593a0"]
    train_batch_id = "b3346be9"
    train_epochs = 1
    train_remove_cross_sequences = true
    train_batch_size = 32
    #sem pridat batch_id a take earlystoppage params

#state.bars, state.indicators, state.cbar_idnicators, state.dailyBars, state.static_inds
#each input groups the same granularity
#first is always highest with target, now - in the future can be in the lowest and is distributed to high-res

#TODO pozor na poradi v predictu musi odpovidat

#this is the target that will be used for label
#we support target resampling, if used on other than highest resolution
[model.target] 
    bars = "close"
    target_reference = "tick_price"
    scaler = "StandardScaler"

[model.input.highres]
    cbar_indicators = ["tick_price", "tick_volume","tick_trades"] #"market_time"
    sequence_length = 75
    scaler = "StandardScaler"
[model.input.lowres]
    bars = ["volume", "close", "open", "high", "low"]
    indicators = ["atr10", "sl_long"]
    sequence_length = 20
    scaler = "StandardScaler"
# [model.input.daily]
#     dailyBars = ["time", "close"]
#     sequence_length = 20

[model.architecture]
    name = "LSTM2Inputs_"  #modelLSTM_ #Conv1D_ "TCN_" "Conv1DcomplexAtt_"  name of file/function with architecture
[model.architecture.params]
    learning_rate = 0.001
[model.architecture.params.early_stopping]
    monitor='mean_squared_error'
    patience=20
    min_delta=0.0001
    mode='min'