    #download_server = "142.132.188.109"
    #upload_server = "142.132.188.109"
    download_server = "0.0.0.0"
    upload_server = "0.0.0.0"
    #upload_server = "5.161.179.223" #where to upload model
    #download_server = "5.161.179.223" #to download batches/runners
    upload = true
[validation] #toto je externi(nasledna) validace (SCALAR(rt test) a VECTOR)
    test_size = 0 #zda se maji splitnout X data pro externi validaci (pozor bere data na trenink)
    runners = ["a37fe8ba-bb87-410d-ba1a-fe46c7b93903"] #runners or batch as sources
    batch = "" #nad konkretnim batchem

[fit] #params that go to Model.fit
    batch_size = 64
    epochs = 3
    validation_split = 0 #validace po kazde epoch (ubira z testovacich dat
    verbose = 'auto' # 0 = silent, 1 = progress bar, 2 = one line per epoch

[fit.callbacks.EarlyStopping]
    monitor='loss' #'mean_squared_error'
    patience=20
    min_delta=0.0001
    mode='min'
# [fit.callbacks.ReduceLROnPlateau] #reduces lr
#     #monitor='mean_squared_error'
#     monitor='val_loss'
#     factor=0.1 #snizi learning rate o 10% kdyz se po 5 epoch nesnizi val_loss
#     patience=5
#     min_lr=0.00001
#     verbose=1

[model]
    name = "Conv1DLSTMAtt" #name that would be used to predict
    version = 0.4
    note = "Conv bar LSTM 2 inputs a Att - novy labeling div th = 0.0008"
    train_runner_ids = ["a37fe8ba-bb87-410d-ba1a-fe46c7b93903"]
    #train_batch_id = "5ea09700"
    train_remove_cross_sequences = true #nyni nefunguje, je true

#this is the target that will be used for label
#we support target resampling, if used on other than highest resolution
[model.target] #target used for labeling, we support target resampling, if used on other than highest resolution
    indicators = "targetema"
    target_reference = "tick_price"
    scaler = "StandardScaler"
[model.input.highres]
    cbar_indicators = ["tick_price", "tick_volume","tick_trades", "daytimetick"]
    sequence_length = 300
    scaler = "StandardScaler"
[model.input.lowres]
    bars = ["vwap","close","open","high","low"]
    indicators = ["daytimebar", "divema", "slope5", "voldiv", "rsi14MA", "emaSlow"]
    sequence_length = 200
    scaler = "StandardScaler"
# [model.input.daily]
#     dailyBars = ["rsi", "volume_sma_divergence", "open", "close"]
#     sequence_length = 25
#     scaler = "StandardScaler"
[model.architecture]
    name = "Conv1DLSTM2InputsAtt_"  #Conv1D3Inputs_ LSTM3Inputs_ #Conv1D_ "TCN_" "Conv1DcomplexAtt_"  name of file/function with architecture
[model.architecture.params] #params that are passed into model function (needed to compile)
    learning_rate = 0.001
#    l2_reg = 0.001 # Added L2 regularization parameter

#novy format?
# [train.sources]
#     #train_runner_ids = ["96fad44c-7a7a-4833-8915-6cc5180593a0"]
#     train_batch_id = "b3346be9"
# [train.sequencing]
#     train_remove_cross_sequences = true
# [train.params]
#     epochs = 1
#     batch_size = 32
